# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://marchforsciencegeneva.org
title: March For Science - Geneva
email: info@marchforsciencegeneva@gmail.com
author: MFS Geneva
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2017 MFS: Geneva. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/mfs_geneva
  - title: github
    url: https://github.com/marchforsciencegeneva/marchforsciencegeneva.github.io
